# Generated by Django 6.0 on 2026-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
