# Generated by Django 5.1 on 2026-01-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_remove_adoptionrequest_phone_lostfoundreport_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
