# Generated by Django 5.1 on 2026-01-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_lostfoundresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LostFoundResponse',
        ),
    ]
