# Generated by Django 5.1 on 2026-01-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_lostfoundresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfoundreport',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
