# Generated by Django 5.1 on 2026-01-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_lostfoundreport_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lostfoundresponse',
            name='phone',
        ),
    ]
