# Generated by Django 6.0 on 2026-01-24 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_initial'),
        ]


    operations = [
        migrations.CreateModel(
            name='PetMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('admin_verified', models.BooleanField(default=False)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='pets.lostfoundreport')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='pets.lostfoundreport')),
            ],
            options={
                'ordering': ('-score', '-matched_on'),
                'unique_together': {('lost_report', 'found_report')},
            },
        ),
    ]
